### ISSUE TITLE
Change Speed Based on Encumbrance and Armor

### ISSUE THREAD

**Issue by bmos** [bmos/TotalEncumbrance#25]
When encumbered, speed is effected as well.
This isn't used for any automation, but it is shown on the charsheet main tab.

See here for how it works (programming all those potential changes might be a real headache!):
https://www.d20pfsrd.com/alignment-description/carrying-capacity/#TOC-Table-Encumbrance-Effects

**Comment by crusopaul** [comment]
Maybe maybe, I do see a big a if statement in the future of this issue. Fingers crossed that effect bonuses already factor into speed if that's a thing

**Comment by bmos** [comment]
They don't but that is a great idea :P
-------- Original Message --------
