### ISSUE TITLE
Color coded encumbrance numbers

### ISSUE THREAD

**Issue by bmos** [bmos/TotalEncumbrance#5]
Rather than building a UI with other boxes to show the penalties from equipment vs from encumbrance, it might be sufficiently helpful and intuitive to color-code the values (red?) when they're coming from encumbrance.

**Comment by bmos** [comment]
Unfortunately this would likely require changing from math.min to an 'if x > y then' scenario.

**Comment by crusopaul** [comment]
Do you mean adding a view element that would have values with a notation like "-10 + red(-6)" where the red element was the encumbrance penalty (for something like a check penalty/spell failure)?

**Comment by bmos** [comment]
I think we would continue only displaying the active number, but make it red if it's from weight

**Comment by crusopaul** [comment]
True. I hadn't thought of that but I think that's a pretty good solution. Checking the maxstattoset == maxstatfromenc equality may require some function reorganization but is certainly doable.

**Comment by bmos** [comment]
oh that's a much simpler approach than I was imagining. nice call.

**Comment by bmos** [comment]
The main issue/hardest part here will be figuring out how to change the color from the script since colors are defined in the xml file color tag.

**Comment by bmos** [comment]
see
https://github.com/bmos/TotalEncumbrance/pull/9
