### ISSUE TITLE
STR bonus from effects doesn't change carrying capacity

### ISSUE THREAD

**Issue by bmos** [bmos/TotalEncumbrance#6]
This is actually kind of a big deal, although it might be really difficult to fix.
Worth looking into. Might be easier to create an extension to add an "item bonus" box to the main tab, although it would be great to count coded effects.

**Comment by crusopaul** [comment]
Big oof. Definitely worth looking into. It would involve an enhancement to the core 3.5 functionality rather than a feature - which... is a pia to implement.

**Comment by bmos** [comment]
Only kind of, those effects are used for some automation already. Might just need to add it as an input for calculating carry capacities.

**Comment by bmos** [comment]
I forgot there is already a box for this, it just has to be filled in manually.
Considering that's how FG is to start with, not a big issue. Just some room for improvement.

**Comment by bmos** [comment]
Effects are saved in the player sheet section of the database.
`<effects>
	<public />
	<id-00001>
		<public />
		<duration type="number">0</duration>
		<init type="number">0</init>
		<isactive type="number">1</isactive>
		<isgmonly type="number">0</isgmonly>
		<label type="string">STR: 2 enhancement</label>
	</id-00001>
</effects>`

Parsing the label tag for anything of the format STR: N T would give us a table of typed strength bonuses from effects. This should then be reduced to only the highest bonus of each type. Finally, a quick sum function would to give current strength bonus from effects.

This number could then be combined with anything entered in the manual strength change box (usually stored in encumbrance.stradj, although we could remap this to a new entry before writing the total back to encumbrance.stradj to have it effect carrying capacity).

**Comment by crusopaul** [comment]
I believe that we will want to use getEffectsBonusByType (line 535 in manager_effect_35E.lua) to get STR bonuses. See line 714 in manager_actor2.lua for call example: example involves a call for AC bonus consideration (key/value equality exists in DataCommon.actypes.) I am seeing some removal logic in getEffectsBonusByType that is commented with something to the effect of "one-off effects." Would STR bonuses ever be one-off effects in 35E?

**Comment by bmos** [comment]
Manager_actor2.lua also has this gem:
Function getAbilityEffectsBonus(rActor, sAbility)
sAbility is fed the input "strength" at 283 of manager_effect_35E.lua along with our old friend rActor.
This might be easy (famous last words).

**Comment by bmos** [comment]
So it turns out that effects aren't stored in charsheet...
They're in combattracker under the same ID that the PC sheet uses.
