### ISSUE TITLE
Deleting item leaves encumbrance

### ISSUE THREAD

**Issue by bmos** [bmos/TotalEncumbrance#7]
Need to trigger RealEncumbrance.applyPenalties when items are deleted from inventory.
Currently, deleting an item that applies encumbrance penalties leaves the penalties active.

**Comment by crusopaul** [comment]
For sure. I've thought about inventory additions/deletions a little bit. My initial thoughts on a fix would be to utilize an onChildUpdate handler on the inventorylist, but I'm not sure if that change would need to replace the current onUpdate to inventorylist.*.carried.* handler or if it would have to be in lieu of it depending on when onChildUpdate is called (changes to subchildren values vs insertion/deletion of children.)

**Comment by bmos** [comment]
I think you mentioned this to me before.
There's actually a great function for this:
https://www.fantasygrounds.com/refdoc/databasenode.xcp#onChildDeleted

**Comment by crusopaul** [comment]
Perfect! I definitely think that this function call on the DB node would not collide with calls to onUpdate to the carried nodes.

**Comment by bmos** [comment]
quick fix!
